добавила маршрутизацию
htmlacademy-react/1801301-six-cities-9 pull request #4
Opened 2022-02-25 11:22 UTC by victoria-buvenova

1. Создан отдельный компонент для страницы «404»
2. добавены маршруты     
    Main /
    Sign In /login
    Favorites /favorites
    Room /offer/:id
3. Создан компонент для описания приватных маршрутов

2022-02-25 13:15 UTC, Mx-Wolf commented
Вообще-то мы говорили, что требуется использовать нижний регистр для именования файлов
Это критерий
https://up.htmlacademy.ru/react/9/criteries#b21

2022-02-25 13:20 UTC, Mx-Wolf requested changes

2022-02-25 13:20 UTC, Mx-Wolf commented on project/src/components/Favorites.tsx
>              <nav className="header__nav">
имя файла перевести в нижний регистр

2022-02-25 13:20 UTC, Mx-Wolf commented on project/src/components/Room.tsx
>              <nav className="header__nav">
имя файла в нижнем регистре

2022-02-25 13:20 UTC, Mx-Wolf commented on project/src/components/app/app.tsx
> +  return (
Все правильно

2022-02-25 13:20 UTC, Mx-Wolf commented on project/src/components/app/example.html
> +<!DOCTYPE html>
Этот файл надо удалить! = это было для тренировки и для понимания пропсов

2022-03-01 10:54 UTC, victoria-buvenova commented on project/src/components/app/example.html
> +<!DOCTYPE html>
удален @Mx-Wolf

2022-03-01 10:55 UTC, victoria-buvenova commented on project/src/components/Room.tsx
>              <nav className="header__nav">
fixed @Mx-Wolf

2022-03-01 10:55 UTC, victoria-buvenova commented on project/src/components/Favorites.tsx
>              <nav className="header__nav">
fixed @Mx-Wolf

2022-03-01 11:00 UTC, Mx-Wolf approved these changes

2022-03-01 11:01 UTC, merged